export enum TextCases {
    lowerCase = 'lowercase',
    upperCase = 'UPPERCASE',
    camelCase = 'camelCase',
    capitalCase = 'Capital Case',
    constantCase = 'CONSTANT_CASE',
    dotCase = 'dot.case',
    headerCase = 'Header-Case',
    noCase = 'no case',
    paramCase = 'param-case',
    pascalCase = 'PascalCase',
    pathCase = 'path/case',
    sentenceCase = 'Sentence case',
    snakeCase = 'snake_case',
}

export enum DateTypes {
    toString = 'String',
    toISOString = 'ISO String',
    toDateString = 'Date String',
    toTimeString = 'Time String',
    toUTCString = 'UTC String',
    toLocaleTimeString = 'Locale Time String',
    toLocaleDateString = 'Locale Date String',
    toLocaleString = 'Locale String',
}

export const TEXT_CASES = [
    TextCases.lowerCase,
    TextCases.upperCase,
    TextCases.camelCase,
    TextCases.capitalCase,
    TextCases.constantCase,
    TextCases.dotCase,
    TextCases.headerCase,
    TextCases.noCase,
    TextCases.paramCase,
    TextCases.pascalCase,
    TextCases.pathCase,
    TextCases.sentenceCase,
    TextCases.snakeCase,
];

export const DATE_TYPES = [
    { value: DateTypes.toString, label: 'String' },
    { value: DateTypes.toISOString, label: 'ISO String' },
    { value: DateTypes.toDateString, label: 'Date String' },
    { value: DateTypes.toTimeString, label: 'Time String' },
    { value: DateTypes.toUTCString, label: 'UTC String' },
    { value: DateTypes.toLocaleTimeString, label: 'Locale Time String' },
    { value: DateTypes.toLocaleDateString, label: 'Locale Date String' },
    { value: DateTypes.toLocaleString, label: 'Locale String' },
];

export const GPT_MODELS = [
    'gpt-4',
    'gpt-3.5-turbo-16k',
    'gpt-3.5-turbo-16k-0613',
    'davinci',
    'text-davinci-001',
    'text-search-curie-query-001',
    'babbage',
    'text-babbage-001',
    'curie-instruct-beta',
    'gpt-4-0314',
    'davinci-similarity',
    'code-davinci-edit-001',
    'text-similarity-curie-001',
    'gpt-4-0613',
    'ada-code-search-text',
    'text-search-ada-query-001',
    'babbage-search-query',
    'text-curie-001',
    'text-search-ada-doc-001',
    'text-search-babbage-query-001',
    'code-search-ada-code-001',
    'curie-search-document',
    'davinci-002',
    'gpt-3.5-turbo-0613',
    'text-search-davinci-query-001',
    'text-search-curie-doc-001',
    'babbage-search-document',
    'babbage-002',
    'babbage-code-search-text',
    'text-embedding-ada-002',
    'gpt-3.5-turbo',
    'davinci-instruct-beta',
    'davinci-search-query',
    'text-similarity-babbage-001',
    'ada-similarity',
    'text-davinci-002',
    'code-search-babbage-text-001',
    'text-similarity-ada-001',
    'text-search-davinci-doc-001',
    'code-search-ada-text-001',
    'ada-search-query',
    'ada-code-search-code',
    'whisper-1',
    'text-davinci-edit-001',
    'davinci-search-document',
    'curie-search-query',
    'babbage-similarity',
    'ada',
    'ada-search-document',
    'text-ada-001',
    'text-similarity-davinci-001',
    'curie-similarity',
    'babbage-code-search-code',
    'code-search-babbage-code-001',
    'text-search-babbage-doc-001',
    'gpt-3.5-turbo-0301',
    'curie',
    'text-davinci-003',
];

export const GPT_OPTIONS = [
    { value: '', label: 'Default' },
    { value: 'What is the meaning of', label: 'Find Meaning' },
    { value: 'Paraphrase the below paragraph.', label: 'Paraphrase' },
    { value: 'Simplify the below paragraph.', label: 'Simplify Complex Paragraph' },
    { value: 'Add comments to the below code.', label: 'Add Code Comments' },
    { value: 'Refactor the below code.', label: 'Refactor Code' },
    { value: 'Explain the below code.', label: 'Explain Code' },
    { value: 'Find the bugs in the below code.', label: 'Find Code Bugs' },
    { value: 'Provide documentation for the below code.', label: 'Document Code' },
    { value: 'Add unit test for the below code.', label: 'Add Unit Test' },
    { value: 'Debug the below code.', label: 'Debug Code' },
    { value: 'Write a script to automate the below task.', label: 'Write Script' },
    { value: 'Summarize the below email.', label: 'Summarize Email' },
    { value: 'Compose a new email with simple english.', label: 'Compose Email' },
    { value: 'Write a reply to the below email.', label: 'Reply to Email' },
    { value: 'Generate a report on the below data.', label: 'Generate Report' },
    { value: 'Analyze the below data.', label: 'Analyze Data' },
    { value: 'Predict the outcome based on the below data.', label: 'Predict Outcome' },
    { value: 'Create a presentation on the below topic.', label: 'Create Presentation' },
    { value: 'Write a review on the below product.', label: 'Write Product Review' },
    { value: 'Write a summary of the below article.', label: 'Summarize Article' },
    { value: 'Write a technical specification for the below product.', label: 'Write Technical Specification' },
    { value: 'Write a product description for the below product.', label: 'Write Product Description' },
    { value: 'Write a user guide for the below software.', label: 'Write User Guide' },
    { value: 'Write a SWOT analysis for the below business.', label: 'Write SWOT Analysis' },
    { value: 'Write a memo for the below topic.', label: 'Write Memo' },
    { value: 'Write a report for the below topic.', label: 'Write Report' },
    { value: 'Write a meeting summary for the below meeting.', label: 'Write Meeting Summary' },
];
