export enum TextCases {
    lowerCase = 'lowercase',
    upperCase = 'UPPERCASE',
    camelCase = 'camelCase',
    capitalCase = 'Capital Case',
    constantCase = 'CONSTANT_CASE',
    dotCase = 'dot.case',
    headerCase = 'Header-Case',
    noCase = 'no case',
    paramCase = 'param-case',
    pascalCase = 'PascalCase',
    pathCase = 'path/case',
    sentenceCase = 'Sentence case',
    snakeCase = 'snake_case',
}

export enum DateTypes {
    toString = 'String',
    toISOString = 'ISO String',
    toDateString = 'Date String',
    toTimeString = 'Time String',
    toUTCString = 'UTC String',
    toLocaleTimeString = 'Locale Time String',
    toLocaleDateString = 'Locale Date String',
    toLocaleString = 'Locale String',
}

export const TEXT_CASES = [
    TextCases.lowerCase,
    TextCases.upperCase,
    TextCases.camelCase,
    TextCases.capitalCase,
    TextCases.constantCase,
    TextCases.dotCase,
    TextCases.headerCase,
    TextCases.noCase,
    TextCases.paramCase,
    TextCases.pascalCase,
    TextCases.pathCase,
    TextCases.sentenceCase,
    TextCases.snakeCase,
];

export const DATE_TYPES = [
    { value: DateTypes.toString, label: 'String' },
    { value: DateTypes.toISOString, label: 'ISO String' },
    { value: DateTypes.toDateString, label: 'Date String' },
    { value: DateTypes.toTimeString, label: 'Time String' },
    { value: DateTypes.toUTCString, label: 'UTC String' },
    { value: DateTypes.toLocaleTimeString, label: 'Locale Time String' },
    { value: DateTypes.toLocaleDateString, label: 'Locale Date String' },
    { value: DateTypes.toLocaleString, label: 'Locale String' },
];

export const GPT_MODELS = [
    'gpt-3.5-turbo-16k',
    'gpt-4',
    'gpt-3.5-turbo-16k-0613',
    'davinci',
    'text-davinci-001',
    'text-search-curie-query-001',
    'babbage',
    'text-babbage-001',
    'curie-instruct-beta',
    'gpt-4-0314',
    'davinci-similarity',
    'code-davinci-edit-001',
    'text-similarity-curie-001',
    'gpt-4-0613',
    'ada-code-search-text',
    'text-search-ada-query-001',
    'babbage-search-query',
    'text-curie-001',
    'text-search-ada-doc-001',
    'text-search-babbage-query-001',
    'code-search-ada-code-001',
    'curie-search-document',
    'davinci-002',
    'gpt-3.5-turbo-0613',
    'text-search-davinci-query-001',
    'text-search-curie-doc-001',
    'babbage-search-document',
    'babbage-002',
    'babbage-code-search-text',
    'text-embedding-ada-002',
    'gpt-3.5-turbo',
    'davinci-instruct-beta',
    'davinci-search-query',
    'text-similarity-babbage-001',
    'ada-similarity',
    'text-davinci-002',
    'code-search-babbage-text-001',
    'text-similarity-ada-001',
    'text-search-davinci-doc-001',
    'code-search-ada-text-001',
    'ada-search-query',
    'ada-code-search-code',
    'whisper-1',
    'text-davinci-edit-001',
    'davinci-search-document',
    'curie-search-query',
    'babbage-similarity',
    'ada',
    'ada-search-document',
    'text-ada-001',
    'text-similarity-davinci-001',
    'curie-similarity',
    'babbage-code-search-code',
    'code-search-babbage-code-001',
    'text-search-babbage-doc-001',
    'gpt-3.5-turbo-0301',
    'curie',
    'text-davinci-003',
];
