export enum TextCases {
    lowerCase = 'lowercase',
    upperCase = 'UPPERCASE',
    camelCase = 'camelCase',
    capitalCase = 'Capital Case',
    constantCase = 'CONSTANT_CASE',
    dotCase = 'dot.case',
    headerCase = 'Header-Case',
    noCase = 'no case',
    paramCase = 'param-case',
    pascalCase = 'PascalCase',
    pathCase = 'path/case',
    sentenceCase = 'Sentence case',
    snakeCase = 'snake_case',
}

export enum DateTypes {
    toString = 'String',
    toISOString = 'ISO String',
    toDateString = 'Date String',
    toTimeString = 'Time String',
    toUTCString = 'UTC String',
    toLocaleTimeString = 'Locale Time String',
    toLocaleDateString = 'Locale Date String',
    toLocaleString = 'Locale String',
}

export const TEXT_CASES = [
    TextCases.lowerCase,
    TextCases.upperCase,
    TextCases.camelCase,
    TextCases.capitalCase,
    TextCases.constantCase,
    TextCases.dotCase,
    TextCases.headerCase,
    TextCases.noCase,
    TextCases.paramCase,
    TextCases.pascalCase,
    TextCases.pathCase,
    TextCases.sentenceCase,
    TextCases.snakeCase,
];

export const DATE_TYPES = [
    { value: DateTypes.toString, label: 'String' },
    { value: DateTypes.toISOString, label: 'ISO String' },
    { value: DateTypes.toDateString, label: 'Date String' },
    { value: DateTypes.toTimeString, label: 'Time String' },
    { value: DateTypes.toUTCString, label: 'UTC String' },
    { value: DateTypes.toLocaleTimeString, label: 'Locale Time String' },
    { value: DateTypes.toLocaleDateString, label: 'Locale Date String' },
    { value: DateTypes.toLocaleString, label: 'Locale String' },
];

export const GPT_MODELS = [
    'gpt-4',
    'gpt-3.5-turbo-16k',
    'gpt-3.5-turbo-16k-0613',
    'davinci',
    'text-davinci-001',
    'text-search-curie-query-001',
    'babbage',
    'text-babbage-001',
    'curie-instruct-beta',
    'gpt-4-0314',
    'davinci-similarity',
    'code-davinci-edit-001',
    'text-similarity-curie-001',
    'gpt-4-0613',
    'ada-code-search-text',
    'text-search-ada-query-001',
    'babbage-search-query',
    'text-curie-001',
    'text-search-ada-doc-001',
    'text-search-babbage-query-001',
    'code-search-ada-code-001',
    'curie-search-document',
    'davinci-002',
    'gpt-3.5-turbo-0613',
    'text-search-davinci-query-001',
    'text-search-curie-doc-001',
    'babbage-search-document',
    'babbage-002',
    'babbage-code-search-text',
    'text-embedding-ada-002',
    'gpt-3.5-turbo',
    'davinci-instruct-beta',
    'davinci-search-query',
    'text-similarity-babbage-001',
    'ada-similarity',
    'text-davinci-002',
    'code-search-babbage-text-001',
    'text-similarity-ada-001',
    'text-search-davinci-doc-001',
    'code-search-ada-text-001',
    'ada-search-query',
    'ada-code-search-code',
    'whisper-1',
    'text-davinci-edit-001',
    'davinci-search-document',
    'curie-search-query',
    'babbage-similarity',
    'ada',
    'ada-search-document',
    'text-ada-001',
    'text-similarity-davinci-001',
    'curie-similarity',
    'babbage-code-search-code',
    'code-search-babbage-code-001',
    'text-search-babbage-doc-001',
    'gpt-3.5-turbo-0301',
    'curie',
    'text-davinci-003',
];

export const GPT_OPTIONS = [
    { value: '', label: 'Default' },
    { value: 'Translate the below sentence to ', label: 'Translate' },
    { value: 'What is the meaning of', label: 'Find Meaning' },
    { value: 'Paraphrase the below paragraph.', label: 'Paraphrase' },
    { value: 'Simplify the below paragraph.', label: 'Simplify Complex Paragraph' },
    { value: 'Write an essay on the below topic.', label: 'Write an essay' },
    { value: 'Write an article on the below topic.', label: 'Write an article' },
    { value: 'Add comments to the below code.', label: 'Add Code Comments' },
    { value: 'Refactor the below code.', label: 'Refactor Code' },
    { value: 'Explain the below code.', label: 'Explain Code' },
    { value: 'Find the bugs in the below code.', label: 'Find Code Bugs' },
    { value: 'Provide documentation for the below code.', label: 'Document Code' },
    { value: 'Compile and run the below code.', label: 'Compile & Run Code' },
    { value: 'Add unit test for the below code.', label: 'Add Unit Test' },
    { value: 'Debug the below code.', label: 'Debug Code' },
    { value: 'Optimize the below code for performance.', label: 'Optimize Code' },
    { value: 'Convert the below code to a different programming language.', label: 'Convert Code' },
    { value: 'Write a function based on the below requirements.', label: 'Write Function' },
    { value: 'Write a class based on the below requirements.', label: 'Write Class' },
    { value: 'Write a script to automate the below task.', label: 'Write Script' },
    { value: 'Design a database schema based on the below requirements.', label: 'Design Database Schema' },
    { value: 'Design a RESTful API based on the below requirements.', label: 'Design API' },
    { value: 'Design a microservice architecture based on the below requirements.', label: 'Design Microservice Architecture' },
    { value: 'Design a software system based on the below requirements.', label: 'Design Software System' },
    { value: 'Summarise the below email.', label: 'Summarise Email' },
    { value: 'Generate a report on the below data.', label: 'Generate Report' },
    { value: 'Analyze the below data.', label: 'Analyze Data' },
    { value: 'Predict the outcome based on the below data.', label: 'Predict Outcome' },
    { value: 'Create a presentation on the below topic.', label: 'Create Presentation' },
    { value: 'Write a review on the below product.', label: 'Write Product Review' },
    { value: 'Write a summary of the below article.', label: 'Summarise Article' },
    { value: 'Write a blog post on the below topic.', label: 'Write Blog Post' },
    { value: 'Write a news report on the below event.', label: 'Write News Report' },
    { value: 'Write a script for the below scenario.', label: 'Write Script' },
    { value: 'Write a business plan for the below idea.', label: 'Write Business Plan' },
    { value: 'Write a marketing plan for the below product.', label: 'Write Marketing Plan' },
    { value: 'Write a sales pitch for the below product.', label: 'Write Sales Pitch' },
    { value: 'Write a user manual for the below product.', label: 'Write User Manual' },
    { value: 'Write a technical specification for the below product.', label: 'Write Technical Specification' },
    { value: 'Write a project proposal for the below idea.', label: 'Write Project Proposal' },
    { value: 'Write a research paper on the below topic.', label: 'Write Research Paper' },
    { value: 'Write a thesis statement for the below topic.', label: 'Write Thesis Statement' },
    { value: 'Write a book review on the below book.', label: 'Write Book Review' },
    { value: 'Write a movie review on the below movie.', label: 'Write Movie Review' },
    { value: 'Write a restaurant review for the below restaurant.', label: 'Write Restaurant Review' },
    { value: 'Write a travel guide for the below location.', label: 'Write Travel Guide' },
    { value: 'Write a recipe for the below dish.', label: 'Write Recipe' },
    { value: 'Write a lesson plan for the below topic.', label: 'Write Lesson Plan' },
    { value: 'Write a resume for the below job description.', label: 'Write Resume' },
    { value: 'Write a cover letter for the below job description.', label: 'Write Cover Letter' },
    { value: 'Write a press release for the below event.', label: 'Write Press Release' },
    { value: 'Write a newsletter for the below topic.', label: 'Write Newsletter' },
    { value: 'Write a social media post for the below topic.', label: 'Write Social Media Post' },
    { value: 'Write a speech for the below occasion.', label: 'Write Speech' },
    { value: 'Write a poem on the below theme.', label: 'Write Poem' },
    { value: 'Write a short story based on the below prompt.', label: 'Write Short Story' },
    { value: 'Write a novel based on the below plot.', label: 'Write Novel' },
    { value: 'Write a song based on the below theme.', label: 'Write Song' },
    { value: 'Write a play based on the below scenario.', label: 'Write Play' },
    { value: 'Write a comic strip based on the below characters.', label: 'Write Comic Strip' },
    { value: 'Write a game design document for the below game idea.', label: 'Write Game Design Document' },
    { value: 'Write a software design document for the below software idea.', label: 'Write Software Design Document' },
    { value: 'Write a patent application for the below invention.', label: 'Write Patent Application' },
    { value: 'Write a grant proposal for the below project.', label: 'Write Grant Proposal' },
    { value: 'Write a business proposal for the below business idea.', label: 'Write Business Proposal' },
    { value: 'Write a legal brief for the below case.', label: 'Write Legal Brief' },
    { value: 'Write a medical report for the below patient.', label: 'Write Medical Report' },
    { value: 'Write a psychological report for the below patient.', label: 'Write Psychological Report' },
    { value: 'Write a financial report for the below company.', label: 'Write Financial Report' },
    { value: 'Write a audit report for the below company.', label: 'Write Audit Report' },
    { value: 'Write a progress report for the below project.', label: 'Write Progress Report' },
    { value: 'Write a performance review for the below employee.', label: 'Write Performance Review' },
    { value: 'Write a product description for the below product.', label: 'Write Product Description' },
    { value: 'Write a user guide for the below software.', label: 'Write User Guide' },
    { value: 'Write a troubleshooting guide for the below product.', label: 'Write Troubleshooting Guide' },
    { value: 'Write a FAQ for the below product.', label: 'Write FAQ' },
    { value: 'Write a white paper on the below topic.', label: 'Write White Paper' },
    { value: 'Write a case study on the below topic.', label: 'Write Case Study' },
    { value: 'Write a technical manual for the below product.', label: 'Write Technical Manual' },
    { value: 'Write a policy document for the below policy.', label: 'Write Policy Document' },
    { value: 'Write a procedure document for the below procedure.', label: 'Write Procedure Document' },
    { value: 'Write a training manual for the below process.', label: 'Write Training Manual' },
    { value: 'Write a meeting agenda for the below meeting.', label: 'Write Meeting Agenda' },
    { value: 'Write a meeting minutes for the below meeting.', label: 'Write Meeting Minutes' },
    { value: 'Write a project plan for the below project.', label: 'Write Project Plan' },
    { value: 'Write a project charter for the below project.', label: 'Write Project Charter' },
    { value: 'Write a risk assessment for the below project.', label: 'Write Risk Assessment' },
    { value: 'Write a SWOT analysis for the below business.', label: 'Write SWOT Analysis' },
    { value: 'Write a market analysis for the below market.', label: 'Write Market Analysis' },
    { value: 'Write a competitive analysis for the below market.', label: 'Write Competitive Analysis' },
    { value: 'Write a business analysis for the below business.', label: 'Write Business Analysis' },
    { value: 'Write a cost benefit analysis for the below project.', label: 'Write Cost Benefit Analysis' },
    { value: 'Write a feasibility study for the below project.', label: 'Write Feasibility Study' },
    { value: 'Write a project evaluation for the below project.', label: 'Write Project Evaluation' },
    { value: 'Write a performance evaluation for the below employee.', label: 'Write Performance Evaluation' },
    { value: 'Write a self evaluation for the below performance.', label: 'Write Self Evaluation' },
    { value: 'Write a peer evaluation for the below performance.', label: 'Write Peer Evaluation' },
    { value: 'Write a job description for the below position.', label: 'Write Job Description' },
    { value: 'Write a job posting for the below position.', label: 'Write Job Posting' },
    { value: 'Write a job offer for the below candidate.', label: 'Write Job Offer' },
    { value: 'Write a rejection letter for the below candidate.', label: 'Write Rejection Letter' },
    { value: 'Write a resignation letter for the below position.', label: 'Write Resignation Letter' },
    { value: 'Write a recommendation letter for the below person.', label: 'Write Recommendation Letter' },
    { value: 'Write a reference letter for the below person.', label: 'Write Reference Letter' },
    { value: 'Write a thank you letter for the below person.', label: 'Write Thank You Letter' },
    { value: 'Write a complaint letter for the below issue.', label: 'Write Complaint Letter' },
    { value: 'Write a sales letter for the below product.', label: 'Write Sales Letter' },
    { value: 'Write a fundraising letter for the below cause.', label: 'Write Fundraising Letter' },
    { value: 'Write a query letter for the below manuscript.', label: 'Write Query Letter' },
    { value: 'Write a cover letter for the below manuscript.', label: 'Write Cover Letter for Manuscript' },
    { value: 'Write a query letter for the below article.', label: 'Write Query Letter for Article' },
    { value: 'Write a cover letter for the below article.', label: 'Write Cover Letter for Article' },
    { value: 'Write a query letter for the below book.', label: 'Write Query Letter for Book' },
    { value: 'Write a cover letter for the below book.', label: 'Write Cover Letter for Book' },
    { value: 'Write a business letter for the below recipient.', label: 'Write Business Letter' },
    { value: 'Write a memo for the below topic.', label: 'Write Memo' },
    { value: 'Write a report for the below topic.', label: 'Write Report' },
    { value: 'Write a meeting summary for the below meeting.', label: 'Write Meeting Summary' },
    { value: 'Write a project proposal for the below project.', label: 'Write Project Proposal' },
    { value: 'Write a project update for the below project.', label: 'Write Project Update' },
    { value: 'Write a budget proposal for the below project.', label: 'Write Budget Proposal' },
    
];
